In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.datasets import load_iris

In [4]:
data = load_iris()

In [5]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
x = pd.DataFrame(columns=data.feature_names,data=data.data)

In [9]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
y = pd.DataFrame(data.target)

In [11]:
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [19]:
# splitting data or hold out cross validation(CV)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=33)

In [20]:
# LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression

In [27]:
lg = LogisticRegression()
lg.fit(x_train,y_train)
lg_predi = lg.predict(x_test)

print(accuracy_score(y_test,lg_predi)) # to find find accuracy score
print('***********')
print('CONFUSION MATRIX :')
print(confusion_matrix(y_test,lg_predi)) # confusion matrix
print('*'*60)
print(classification_report(y_test,lg_predi)) # classification report

0.94
***********
CONFUSION MATRIX :
[[14  0  0]
 [ 0 16  0]
 [ 0  3 17]]
************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.84      1.00      0.91        16
           2       1.00      0.85      0.92        20

    accuracy                           0.94        50
   macro avg       0.95      0.95      0.94        50
weighted avg       0.95      0.94      0.94        50



In [44]:
# CROSS VALIDATION
from sklearn.model_selection import cross_val_score
# here no need to split the data Cv will automatically split the data
# cv=5
score = cross_val_score(lg,x,y,cv=5) # here there are 4 parameters (model name,x,y,cv=)
print(score)
# we will get mean by dividing total number of score by cv
print(score.mean())
print(score.std())

[0.96666667 1.         0.93333333 0.96666667 1.        ]
0.9733333333333334
0.02494438257849294


In [45]:
# KFold cross validation

from sklearn.model_selection import KFold
#KFold(n_splits=5)

KFold = KFold(5)
scorekfold = cross_val_score(lg,x,y,cv=KFold)
print(scorekfold)
print(scorekfold.mean())
print(scorekfold.std())

[1.         1.         0.86666667 0.93333333 0.83333333]
0.9266666666666665
0.06798692684790378


In [46]:
# DECISION TREE CLASSIFIER
from sklearn.tree import DecisionTreeClassifier

In [52]:
# if in criterion nothing is given by default model select automatically gini index
dtc = DecisionTreeClassifier(criterion='entropy')# here criterion is given in entropy
dtc.fit(x_train,y_train)
dtc_predi = dtc.predict(x_test)

print(accuracy_score(y_test,dtc_predi))
print('***********')
print('CONFUSION MATRIX :')
print(confusion_matrix(y_test,dtc_predi))
print('*'*60)
print(classification_report(y_test,dtc_predi))

0.92
***********
CONFUSION MATRIX :
[[14  0  0]
 [ 0 16  0]
 [ 0  4 16]]
************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.80      1.00      0.89        16
           2       1.00      0.80      0.89        20

    accuracy                           0.92        50
   macro avg       0.93      0.93      0.93        50
weighted avg       0.94      0.92      0.92        50



In [53]:
score_dtc = cross_val_score(dtc,x,y,cv=5)
print(score_dtc)
print(score_dtc.mean())
print(score_dtc.std())

[0.96666667 0.96666667 0.9        0.96666667 1.        ]
0.9600000000000002
0.03265986323710903


In [55]:
# SUPPORT VECTOR MACHINE
from sklearn.svm import SVC

svc = SVC(kernel='linear')
svc.fit(x_train,y_train)
svc_predi = svc.predict(x_test)

print(accuracy_score(y_test,svc_predi))
print('***********')
print('CONFUSION MATRIX :')
print(confusion_matrix(y_test,svc_predi))
print('*'*60)
print(classification_report(y_test,svc_predi))

0.96
***********
CONFUSION MATRIX :
[[14  0  0]
 [ 0 16  0]
 [ 0  2 18]]
************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.89      1.00      0.94        16
           2       1.00      0.90      0.95        20

    accuracy                           0.96        50
   macro avg       0.96      0.97      0.96        50
weighted avg       0.96      0.96      0.96        50



In [56]:
svc_score = cross_val_score(svc,x,y,cv=5)

print(svc_score)
print(svc_score.mean())
print(svc_score.std())

[0.96666667 1.         0.96666667 0.96666667 1.        ]
0.9800000000000001
0.016329931618554516


In [57]:
# LEAVE ONE OUT CROSS VALIDATION
# it takes more time to execute

from sklearn.model_selection import LeaveOneOut

loocv = LeaveOneOut()

score1 = cross_val_score(dtc,x,y,cv=loocv)
print(score1)
print(score1.mean())
print(score1.std())

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
0.96
0.19595917942265423
